# Generated by Django 4.1.2 on 2022-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_posts_options_alter_posts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
