# Generated by Django 4.1.2 on 2022-11-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_posts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='upload_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.posts')),
            ],
            options={
                'verbose_name': 'изображение для поста',
                'verbose_name_plural': 'Изображения для постов',
            },
        ),
    ]
