# Generated by Django 4.1.2 on 2022-11-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('h2', models.CharField(max_length=200, verbose_name='Предописание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('display', models.BooleanField(default=False, verbose_name='Отображать на сайте?')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='Безымянный', max_length=30, verbose_name='Имя')),
                ('content', models.TextField(max_length=500, verbose_name='Содержание сообщения')),
                ('service', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'заказ услуг',
                'verbose_name_plural': 'Заказы услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения стоимости')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'цена на услугу',
                'verbose_name_plural': 'Цены на услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/services/%Y/%m/%d/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'изображение для услуги',
                'verbose_name_plural': 'Изображения для услуг',
            },
        ),
    ]
