# Generated by Django 4.1.2 on 2022-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/%Y/%m/%d/'),
        ),
    ]
