# Generated by Django 4.1.2 on 2022-11-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='foreign_price',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость для иномарок (не обяз)'),
        ),
    ]
