# Generated by Django 4.1.2 on 2022-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprice_foreign_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='foreign_price',
            field=models.CharField(max_length=30, null=True, verbose_name='Стоимость для иномарок (не обяз)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Стоимость'),
        ),
    ]
