# Generated by Django 4.1.2 on 2022-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_serviceprice_foreign_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='foreign_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Стоимость для иномарок (не обяз)'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Единица измерения стоимости'),
        ),
    ]
