export const REQUEST_CATEGORIES = "API/REQUEST_CATEGORIES"
export const REQUEST_PRODUCTS = "API/REQUEST_PRODUCTS"
export const REQUEST_ONE_PRODUCT = "API/REQUEST_ONE_PRODUCT"
export const REQUEST_SUBCATEGORIES = "API/REQUEST_SUBCATEGORIES"
export const FETCH_CATEGORIES = "API/FETCH_CATEGORIES"
export const FETCH_PRODUCTS = "API/FETCH_PRODUCTS"
export const FETCH_ONE_PRODUCT = "API/FETCH_ONE_PRODUCT"
export const FETCH_SUBCATEGORIES = "API/FETCH_SUBCATEGORIES"


export const INIT_RESET_SUBCATEGORIES = "API/INIT_RESET_SUBCATEGORIES"
export const RESET_SUBCATEGORIES = "API/RESET_SUBCATEGORIES"