# Generated by Django 4.1.2 on 2022-10-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_email_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.CharField(default='Безымянный', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар'),
        ),
    ]
