# Generated by Django 4.1.2 on 2022-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_name_client_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_client',
            field=models.CharField(default='Безымянный', max_length=20, verbose_name='Имя клиента'),
        ),
    ]
