# Generated by Django 4.1.2 on 2022-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
