# Generated by Django 4.1.2 on 2022-10-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_question_alter_order_name_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='Безымянный', max_length=30, verbose_name='Имя')),
                ('content', models.TextField(max_length=500, verbose_name='Содержание сообщения')),
                ('service', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'заказ услуг',
                'verbose_name_plural': 'Заказы услуг',
            },
        ),
    ]
