# Generated by Django 4.1.2 on 2022-11-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_serviceorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
